// import maintenancePool from "../config/db.js";
import { maintenancePool } from "../../config/db.js";


export const insertMaintenanceTask = async (data) => {
  // Task_No is now auto-generated by database sequence: 'TM-' || LPAD(nextval('maintenance_task_seq')::text, 3, '0')
  const query = `
    INSERT INTO maintenance_task_assign (
      time_stamp,
      serial_no,
      machine_name,
      given_by,
      doer_name,
      task_type,
      machine_area,
      part_name,
      need_sound_test,
      temperature,
      enable_reminders,
      require_attachment,
      task_start_date,
      frequency,
      description,
      priority,
      machine_department,
      doer_department,
      division
    )
    VALUES (
      $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19
    )
    RETURNING *;
  `;

  // ✅ Convert DD/MM/YYYY → YYYY-MM-DD (PostgreSQL format)
  let cleanDate = null;
  if (data.task_start_date) {
    const parts = data.task_start_date.split(/[\/\s:]/);
    if (parts.length >= 3) {
      const [day, month, year] = parts;
      cleanDate = `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
    }
  }

  const values = [
    data.time_stamp || new Date(),
    data.serial_no,
    data.machine_name,
    data.given_by,
    data.doer_name,
    data.task_type,
    data.machine_area,
    data.part_name,
    data.need_sound_test,
    data.temperature,
    data.enable_reminders,
    data.require_attachment,
    cleanDate, // ✅ properly formatted
    data.frequency,
    data.description,
    data.priority,
    data.machine_department,
    data.doer_department,
    data.division // NEW
  ];

  try {
    const result = await maintenancePool.query(query, values);
    return result.rows[0];
  } catch (err) {
    console.error("❌ Database insert error:", err.message);
    throw err;
  }
};

/**
 * ✅ Fetch all maintenance tasks
 */
export const getAllMaintenanceTasks = async () => {
  const query = `
    SELECT 
      task_no, serial_no, machine_name, given_by, doer_name, 
      task_type, machine_area, part_name, need_sound_test, 
      temperature, enable_reminders, require_attachment, 
      task_start_date, frequency, description, priority, 
      machine_department, doer_department, division
    FROM maintenance_task_assign
    ORDER BY id DESC;
  `;
  const result = await maintenancePool.query(query);
  return result.rows;
};




export const bulkInsertMaintenanceTasks = async (tasksArray) => {
  const client = await maintenancePool.connect();

  try {
    await client.query("BEGIN");

    const query = `
      INSERT INTO maintenance_task_assign (
        time_stamp,
        serial_no,
        machine_name,
        given_by,
        doer_name,
        task_type,
        machine_area,
        part_name,
        need_sound_test,
        temperature,
        enable_reminders,
        require_attachment,
        task_start_date,
        frequency,
        description,
        priority,
        machine_department,
        doer_department,
        division
      )
      SELECT
        t.time_stamp::timestamptz,
        t.serial_no,
        t.machine_name,
        t.given_by,
        t.doer_name,
        t.task_type,
        t.machine_area,
        t.part_name,
        t.need_sound_test,
        t.temperature,
        t.enable_reminders,
        t.require_attachment,
        to_timestamp(t.task_start_date, 'DD/MM/YYYY HH24:MI:SS')::date,
        t.frequency,
        t.description,
        t.priority,
        t.machine_department,
        t.doer_department,
        t.division
      FROM jsonb_to_recordset($1::jsonb) AS t(
        time_stamp text,
        serial_no text,
        machine_name text,
        given_by text,
        doer_name text,
        task_type text,
        machine_area text,
        part_name text,
        need_sound_test boolean,
        temperature text,
        enable_reminders boolean,
        require_attachment boolean,
        task_start_date text,
        frequency text,
        description text,
        priority text,
        machine_department text,
        doer_department text,
        division text
      )
      RETURNING task_no;
    `;

    const result = await client.query(query, [
      JSON.stringify(tasksArray),
    ]);

    await client.query("COMMIT");
    return result.rows;

  } catch (err) {
    await client.query("ROLLBACK");
    console.error("❌ Bulk insert error:", err.message);
    throw err;
  } finally {
    client.release();
  }
};


