name: Node.js CI/CD

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build --if-present

      - name: Restart backend
        run: |
          pm2 restart sagargroup-backend --update-env || pm2 start server.js --name sagargroup-backend
          pm2 save